"""
build_database.py

Purpose:
Convert the synthetic spreadsheet-style CSV files into a local SQLite database.

Why SQLite:
SQLite is lightweight, file-based, and easy to inspect. For a portfolio demo,
it shows the database design without requiring a server, cloud account, or
private credentials.

Privacy note:
The database generated by this script contains synthetic demo records only.
A real version would need authentication, encryption, permissions, audit logs,
and a clear data-retention policy.
"""

from pathlib import Path
import sqlite3
import pandas as pd

# Project paths. Using relative paths keeps the project portable for GitHub.
ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
OUTPUT_DIR = ROOT / "outputs"
DB_PATH = OUTPUT_DIR / "housing_navigation_demo.db"


def main() -> None:
    """Create a fresh SQLite database from the mock CSV files."""
    OUTPUT_DIR.mkdir(exist_ok=True)

    # Each CSV becomes one table.
    # The table names are deliberately simple so nontechnical reviewers can
    # understand the data model quickly.
    tables = {
        "families": pd.read_csv(DATA_DIR / "families_mock.csv"),
        "landlords": pd.read_csv(DATA_DIR / "landlords_mock.csv"),
        "resources": pd.read_csv(DATA_DIR / "resources_mock.csv"),
        "placements": pd.read_csv(DATA_DIR / "placements_mock.csv"),
    }

    # Open a connection to the SQLite database file.
    # if_exists="replace" makes the script repeatable: each run rebuilds
    # the demo database from the source CSVs.
    with sqlite3.connect(DB_PATH) as conn:
        for table_name, df in tables.items():
            df.to_sql(table_name, conn, if_exists="replace", index=False)

    print(f"Created database: {DB_PATH}")


if __name__ == "__main__":
    main()
